### ISSUE TITLE
knife-vsphere-1.2.12/lib/chef/knife/vsphere_vm_clone.rb:581:in `block in generate_clone_spec': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by swalberg** [chef-partners/knife-vsphere#275]
After upgrading to 1.2.12 from an older version, 

```
CPUS=4 RAM=8 SERVER=xxx ZONE=yyyy ENVIRONMENT=staging
knife vsphere vm clone $SERVER --template="CentOS_6.7_Template_16GB_v1.6" --json-attributes='{ "tags": ["app:sso"] }' --cvlan="97-INFRA-PROJECT-TOOLS" --cips dhcp --chostname=$SERVER --cdomain=$ZONE --run-list="$RUNLIST" --start  --fqdn=$SERVER.$ZONE --distro chef-full --bootstrap --cdnsips=1.2.3.4 --cdnssuffix=$ZONE --node-name=$SERVER.$ZONE $EXTRA --environment $ENVIRONMENT  --bootstrap-version 12.8.1
```

Gives 
```
knife-vsphere-1.2.12/lib/chef/knife/vsphere_vm_clone.rb:581:in `block in generate_clone_spec': undefined method `[]' for nil:NilClass (NoMethodError)```

Fixed by adding `--cmacs auto`. Likely a regression introduced by #273 as the hash there is only defined if `--cmacs` is set.

**Comment by kozmikyak** [comment]
Ouch.  I think this is the reason for one of the "if" blocks that I was asked to remove--it prevented it from trying to access the cmacs array if --cmacs wasn't used.

I can try adding that "if" block back in.

**Comment by kozmikyak** [comment]
It was a different oversight than I thought it was.  Did a pull request.

**Comment by swalberg** [comment]
You are too far ahead of me... Was going to look at it this afternoon ;) Thanks so much!
